package code_fb_cg.mapper;

import code_fb_cg.entity.TpCgordertrace;

public interface TpCgordertraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGORDERTRACE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGORDERTRACE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insert(TpCgordertrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGORDERTRACE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insertSelective(TpCgordertrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGORDERTRACE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    TpCgordertrace selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGORDERTRACE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKeySelective(TpCgordertrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGORDERTRACE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKey(TpCgordertrace record);
    
    int insertTpCgordertraceMapper(TpCgordertrace tc);
}