package code_fb_cg.mapper;

import code_fb_cg.entity.TpCggoodstype;

public interface TpCggoodstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGGOODSTYPE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGGOODSTYPE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insert(TpCggoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGGOODSTYPE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insertSelective(TpCggoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGGOODSTYPE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    TpCggoodstype selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGGOODSTYPE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKeySelective(TpCggoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGGOODSTYPE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKey(TpCggoodstype record);
}