package code_fb_cg.mapper;

import code_fb_cg.entity.TpCgdispose;

public interface TpCgdisposeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDISPOSE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDISPOSE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insert(TpCgdispose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDISPOSE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insertSelective(TpCgdispose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDISPOSE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    TpCgdispose selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDISPOSE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKeySelective(TpCgdispose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDISPOSE
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKey(TpCgdispose record);
}