package code_fb_cg.mapper;

import code_fb_cg.entity.TpCgdept;

public interface TpCgdeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDEPT
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDEPT
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insert(TpCgdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDEPT
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insertSelective(TpCgdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDEPT
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    TpCgdept selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDEPT
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKeySelective(TpCgdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGDEPT
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKey(TpCgdept record);
}