package code_fb_cg.mapper;

import code_fb_cg.entity.TpCgqualitybook;

public interface TpCgqualitybookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGQUALITYBOOK
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGQUALITYBOOK
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insert(TpCgqualitybook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGQUALITYBOOK
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int insertSelective(TpCgqualitybook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGQUALITYBOOK
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    TpCgqualitybook selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGQUALITYBOOK
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKeySelective(TpCgqualitybook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TP_CGQUALITYBOOK
     *
     * @mbg.generated Sat Aug 18 16:38:04 CST 2018
     */
    int updateByPrimaryKey(TpCgqualitybook record);
}